name: Warmup Gradle & Pub Cache for Offline Build

on:
  workflow_dispatch:

jobs:
  warmup:
    runs-on: ubuntu-latest

    env:
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

    steps:
      # Checkout پروژه
      - name: Checkout project
        uses: actions/checkout@v4

      # نصب Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.9'

      # دانلود Pub dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # Debug مسیرها و فایل‌ها
      - name: Debug paths
        run: |
          echo "Root dir: $(pwd)"
          ls -la
          cd android
          echo "Android dir: $(pwd)"
          ls -la

      # دانلود Gradle dependencies (Debug + Release)
      - name: Warmup Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon --refresh-dependencies
          ./gradlew assembleRelease --no-daemon

      # Zip کردن Gradle cache
      - name: Zip Gradle Cache
        run: zip -r gradle-cache.zip .gradle

      # Zip کردن Pub cache
      - name: Zip Pub Cache
        run: zip -r pub-cache.zip ~/.pub-cache

      # Upload Artifact برای دانلود
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: offline-caches
          path: |
            gradle-cache.zip
            pub-cache.zip
